const items = [
  {
      id: '001',
      image: 'image/1.jpg.jpg',
      company_name: 'Carlton London',
      item_name: 'Rhodium-Plated CZ Floral Studs',
      original_price: 1045,
      current_price: 606,
      discount_percentage: `(42% OFF)`,
      return_period: 14,
      delivery_date: '10 Oct 2024',
      rating: {
          stars: 4.5,
          noofReviews: `1.3k`,
      },
    },
   {
  id: '02',
  image: 'image/2jpg.jpg',
  company_name: 'CUKOO',
  item_name: 'Women Padded Halter Neck Swimming Dress',
  original_price: 2599,
  current_price: 1507,
  discount_percentage:`(42% OFF)`,
  return_period: 14,
   delivery_date: '10 Oct 2024',
  rating: {
      stars: 4.3,
      noofReviews: `1.3k`,
  },
},
  {
    id: '003',
    image: 'image/3jpg.jpg',
    company_name: 'NUEVOSDAMAS',
    item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
    original_price: 1599,
    current_price: 495,
    discount_percentage: `(42% OFF)`,
    return_period: 14,
    delivery_date: '10 Oct 2024',
    rating: {
        stars: 4.1,
        noofReviews: `1.3k`,
    },
  },
    {
      id: '004',
      image: 'image/4jpg.jpg',
      ccompany_name: 'ADIDAS',
      item_name: 'Indian Cricket ODI Jersey',
      original_price: 999,
      current_price: 999,
      discount_percentage:`(42% OFF)`,
      return_period: 14,
      delivery_date: '10 Oct 2024',
      rating: {
          stars: 5.0,
          noofReviews:`1.3k`,
      },
    },
      {
        id: '005',
        image: 'image/5jpg.jpg',
        company_name: 'Roadster',
        item_name: 'Pure Cotton ',
        original_price: 1399,
        current_price: 489,
        discount_percentage:`(42% OFF)`,
        return_period: 14,
      delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            noofReviews: `1.3k`,
        },
      },
      {
        id: '006',
        image: 'image/6jpg.jpg',
        company_name: 'Roadster',
        item_name: 'Pure Cotton ',
        original_price: 1399,
        current_price: 489,
        discount_percentage:`(42% OFF)`,
        return_period: 14,
      delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            noofReviews: `1.3k`,
        },
      },
      {
        id: '007',
        image: 'image/10jpg.jpg',
        company_name: 'Roadster',
        item_name: 'shoes ',
        original_price: 1399,
        current_price: 489,
        discount_percentage:`(42% OFF)`,
        return_period: 14,
      delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            noofReviews: `1.3k`,
        },
      },
      {
        id: '008',
        image: 'image/9jpg.jpg',
        company_name: 'Roadster',
        item_name: 'Pure Cotton ',
        original_price: 1399,
        current_price: 489,
        discount_percentage:`(42% OFF)`,
        return_period: 14,
      delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            noofReviews: `1.3k`,
        },
      },

      {
        id: '009',
        image: 'image/12jpg.jpg',
        company_name: 'Roadster',
        item_name: 'Pure Cotton ',
        original_price: 1399,
        current_price: 489,
        discount_percentage:`(42% OFF)`,
        return_period: 14,
      delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            noofReviews: `1.3k`,
        },
      },
    ];